INSERT INTO modules (week, day, topic)
VALUES
(0, 0, 'Other...'),
(1, 1, 'Organizing Our Code'),
(1, 1, 'Bootcamp Reference Guide'),
(1, 1, 'How to Use Compass'),
(1, 1, 'So what''s a gist, anyway?'),
(1, 1, 'What should I do for Lunch?'),
(1, 1, 'Linting and ESLint Setup'),
(1, 1, 'Linting Our Lunch'),
(1, 1, 'Git, Markdown, and  the Dev Workflow'),
(1, 1, 'Command Line Args'),
(1, 1, 'Adding Numbers'),
(1, 1, 'Welcome to Lotide'),
(1, 1, 'Make Lotide Directory'),
(1, 1, 'Implement assertEqual'),
(1, 1, 'ES6 Template Literals'),
(1, 1, 'Improve assertEqual'),
(1, 1, 'Implement head'),
(1, 1, 'Implement tail'),
(1, 1, 'Intro to Programming'),
(1, 1, 'Peer Mentoring'),
(1, 1, 'Reversing a String'),
(1, 1, 'Pig Latin Translator'),
(1, 1, 'Loopy Lighthouse Refactor'),
(1, 1, 'Important keyboard shortcuts'),
(1, 2, 'About Pair Programming'),
(1, 2, 'Minimum Values'),
(1, 2, 'Solving Problems With Pseudocode'),
(1, 2, 'Joining Concepts'),
(1, 2, 'Function Best Practices - Introduction'),
(1, 2, 'Function Best Practices - Rolling Dice'),
(1, 2, 'Scope in Javascript'),
(1, 2, 'Getting Comfortable with Error Messages'),
(1, 2, 'Debugging Errors'),
(1, 2, 'Fixing Buggy Code Part 1 - Console Logs'),
(1, 2, 'Coercion and Truthy/Falsey'),
(1, 2, 'Functions, Variables, and Debugging in JavaScript'),
(1, 2, 'Implement eqArrays'),
(1, 2, 'Implement assertArraysEqual'),
(1, 2, 'Implement without'),
(1, 2, 'Password Obfuscator'),
(1, 2, 'Implement flatten'),
(1, 2, 'Debug I - Palindrome'),
(1, 2, 'Debug II - Print In Frame'),
(1, 2, 'Debug III - calculateDayInYear'),
(1, 2, 'Function Best Practices - Refactor I'),
(1, 2, 'Function Best Practices - Refactor II'),
(1, 3, 'A Thought About Goals'),
(1, 3, 'Implement middle'),
(1, 3, 'Primitive Data Types'),
(1, 3, 'Create objects Directory'),
(1, 3, 'Objects - Basic Concepts'),
(1, 3, 'Objects - Iteration'),
(1, 3, 'Implement countOnly in Lotide'),
(1, 3, 'Implement countLetters in Lotide'),
(1, 3, 'Implement letterPositions'),
(1, 3, 'Implement findKeyByValue in Lotide'),
(1, 3, 'Implement eqObjects'),
(1, 3, 'Implement assertObjectsEqual'),
(1, 3, 'JavaScript Objects'),
(1, 3, 'Pair Programming - Raisin'' Arizona'),
(1, 3, 'More on Primitives and Objects in JS'),
(1, 3, 'Objects - Sales Tax'),
(1, 3, 'Social Network Analysis - Part I'),
(1, 4, 'Create funcs Directory'),
(1, 4, 'Functions As Objects'),
(1, 4, 'Anonymous Functions'),
(1, 4, 'Arrow Functions'),
(1, 4, 'First Class Functions'),
(1, 4, 'Filtering With Callbacks'),
(1, 4, 'Higher Order Functions'),
(1, 4, 'Using Map'),
(1, 4, 'Implement Map'),
(1, 4, 'Callbacks'),
(1, 4, 'Implement takeUntil'),
(1, 4, 'Implement findKey'),
(1, 4, 'First date with Vim'),
(1, 4, 'Pair Programming - The Swapper'),
(1, 4, 'Using Map II - Pythagorean'),
(1, 4, 'Callbacks - For Sorting'),
(1, 4, 'Prep Katas Revisit &amp; Cleanup'),
(1, 4, 'Closures'),
(1, 4, 'Using Closures'),
(1, 4, 'Using Closures II'),
(1, 4, 'Closures'),
(1, 5, 'Mock Programming Test'),
(1, 5, 'Rubber Duck Debugging'),
(1, 5, 'Troubleshooting Tips'),
(1, 5, 'ES6'),
(1, 5, 'Music Library'),
(1, 5, 'Object methods and ''this'''),
(1, 5, 'Music Library With Methods'),
(1, 5, 'Arrow Functions and this'),
(1, 5, 'Introduction to Recursion'),
(1, 5, 'Summing with Recursion (Example)'),
(1, 5, 'More Recursion'),
(1, 5, 'Recursion Recap'),
(1, 5, 'Sum From a to b Recursively'),
(1, 5, 'Sum Array of Numbers'),
(1, 5, 'Fun Fun Recursion'),
(1, 5, 'Recursive eqObjects'),
(1, 5, 'Recursive eqArrays'),
(1, 5, 'Solving n! Using Recursion'),
(1, 5, 'Properties of Recursive Algorithms'),
(1, 5, 'Problem Solving - Luhn'),
(1, 5, 'Problem Solving - Stock Market'),
(1, 5, 'Problem Solving - Poppin Bottles'),
(1, 5, 'Dijkstra was right about recursion'),
(1, 6, 'Introduction to Modules'),
(1, 6, 'Packages and npm'),
(1, 6, 'Packages and Modules'),
(1, 6, 'Automated Testing'),
(1, 6, 'Introduction to Unit Testing'),
(1, 6, 'Mocha and Chai Intro'),
(1, 6, 'Running Tests with Mocha'),
(1, 6, 'Should I Buy This Car'),
(1, 6, 'Name Formatter'),
(1, 6, 'Plagiarism Is A Thing'),
(1, 6, 'Why Tech Interviews'),
(1, 6, 'What Tech Interviews'),
(2, 1, 'Lotide Refactor Example'),
(2, 1, 'Refactor tail'),
(2, 1, 'Refactor eqArrays'),
(2, 1, 'Refactor assertArraysEqual'),
(2, 1, 'Refactor middle'),
(2, 1, 'Incorporate Mocha and Chai'),
(2, 1, 'Refactor with Mocha and Chai I'),
(2, 1, 'Exporting All Functions I'),
(2, 1, 'Exporting All Functions II'),
(2, 1, 'Object Shorthand in ES6'),
(2, 1, 'Implement Object Shorthand'),
(2, 1, 'Publishing Lotide To npm'),
(2, 1, 'Submitting Lotide'),
(2, 1, 'Title Case - Kata'),
(2, 1, 'Intro to Async Control Flow'),
(2, 1, 'setTimeout Introduction'),
(2, 1, 'More Lotide Cleanup'),
(2, 1, 'Caesar Cipher - Kata'),
(2, 2, 'Create async Directory'),
(2, 2, 'setTimeout Practice'),
(2, 2, 'Animated Sentence'),
(2, 2, 'Spinner I'),
(2, 2, 'Spinner II'),
(2, 2, 'Simple Timer'),
(2, 2, 'Event Handling and User Input'),
(2, 2, 'Fun Profile Generator'),
(2, 2, 'Asynchronous Return Values'),
(2, 2, 'Testing Asynchronous Return Values'),
(2, 2, 'Pair Programming - There Is No Spoon'),
(2, 2, 'Interactive Timer'),
(2, 2, 'Intro to Networking and TCP'),
(2, 2, 'Intro to net'),
(2, 3, 'Multiplayer Snake Game 🐍'),
(2, 3, 'Client Setup'),
(2, 3, 'Connect to the Server'),
(2, 3, 'Connection module'),
(2, 3, 'Snake Initials'),
(2, 3, 'Move Commands'),
(2, 3, 'Stdin Setup'),
(2, 3, 'Input Module'),
(2, 3, 'WASD Movement'),
(2, 3, 'Sending Messages'),
(2, 3, 'Constants Module'),
(2, 3, 'HTTP Introduction'),
(2, 3, 'HTTP uses TCP'),
(2, 3, 'Using request Library'),
(2, 3, 'Page Downloader'),
(2, 3, 'Pair Programming - Word Search'),
(2, 3, 'Take a Break And Play'),
(2, 3, 'File Server'),
(2, 4, 'JSON'),
(2, 4, 'What is an API'),
(2, 4, 'Cats as a Service'),
(2, 4, 'Testing Cats as a Service'),
(2, 4, 'JSON'),
(2, 4, 'ISS Spotter I'),
(2, 4, 'ISS Spotter II'),
(2, 4, 'ISS Spotter III'),
(2, 4, 'ISS Spotter IV'),
(2, 4, 'Promises Intro'),
(2, 4, 'ISS Spotter With Promises'),
(2, 4, 'Creating Promises'),
(2, 4, 'findFriend - Kata'),
(2, 5, 'Programming Test 2'),
(2, 5, 'Introduction to Object Oriented Programming'),
(2, 5, 'Simple OOP in JavaScript (Review)'),
(2, 5, 'Simple OOP in JavaScript'),
(2, 5, 'Todo List'),
(2, 5, 'OOP in Javascript Disclaimer'),
(2, 5, 'OOP Part 1: Classes &amp; Instances'),
(2, 5, 'OOP Part 2: Inheritance'),
(2, 5, 'OOP Part 3: Super'),
(2, 5, 'OOP Part 4: Getters and Setters'),
(2, 5, 'ES6 OOP Using Classes'),
(2, 5, 'LightCoin (LHL)'),
(2, 5, 'OOP Best Practices'),
(2, 5, 'OOP Best Practices'),
(2, 5, 'OOP Conclusion'),
(2, 5, 'Bloop! Hello Fishes'),
(2, 5, 'Objects in JavaScript'),
(2, 5, 'You Don''t Know JavaScript Objects'),
(2, 6, 'How JS Actually Works'),
(2, 6, 'Promises - Video Review'),
(2, 6, 'Clean Code'),
(2, 6, 'Command Line cURL'),
(2, 6, 'Character Encoding'),
(2, 6, 'Character Encoding'),
(2, 6, 'Domain Name System'),
(2, 6, 'Digging DNS - An Exercise'),
(2, 6, 'DNS'),
(2, 6, 'HTTP Server'),
(2, 6, 'Express Tutorial'),
(3, 1, 'A Reminder About Evaluated Projects'),
(3, 1, 'HTTP'),
(3, 1, 'Our First Web Server'),
(3, 1, 'TinyApp &amp; Express Setup'),
(3, 1, 'What is a Template Engine'),
(3, 1, 'Understanding res.render'),
(3, 1, 'Template Engine - EJS'),
(3, 1, 'CRUD and HTTP'),
(3, 1, 'URL Shortening (Part 1)'),
(3, 1, 'URL Shortening (Part 2)'),
(3, 1, 'Express'),
(3, 2, 'Nodemon'),
(3, 2, 'Deleting URLs'),
(3, 2, 'Updating URLs'),
(3, 2, 'CRUD over HTTP'),
(3, 2, 'Intro to Git Branches'),
(3, 2, 'Intro to Cookies'),
(3, 2, 'Cookies in Express'),
(3, 2, 'Cookies and Domains'),
(3, 3, 'User Registration Form'),
(3, 3, 'Registering New Users'),
(3, 3, 'Registration Errors'),
(3, 3, 'A New Login Page'),
(3, 3, 'Refactoring the Login Route'),
(3, 3, 'Basic Permission Features'),
(3, 3, 'More Permission Features'),
(3, 4, 'Storing Passwords Securely'),
(3, 4, 'Storing Passwords Securely'),
(3, 4, 'Switching to Encrypted Cookies'),
(3, 4, 'Cookies and Sessions'),
(3, 4, 'Testing Helper Functions'),
(3, 4, 'Submit Project for Evaluation'),
(3, 4, 'Update Compass Profile'),
(3, 4, 'REST'),
(3, 4, 'Method Override'),
(3, 4, 'Analytics'),
(3, 5, 'Programming Test 3'),
(3, 5, 'Data Structures Intro'),
(3, 5, 'Intro to Trees: Org charts!'),
(3, 5, 'Trees'),
(3, 5, 'Intro to Trees: Vampr!'),
(3, 5, 'Tree Traversal: Org charts!'),
(3, 5, 'Tree Traversal'),
(3, 5, 'Tree Traversal: Vampr!'),
(3, 6, 'What is a Stack'),
(3, 6, 'HTML and CSS - Basic Intros'),
(3, 6, 'HTML'),
(3, 6, 'IDs vs Classes'),
(3, 6, 'Event-Driven Architecture - A brief Intro'),
(3, 6, 'The DOM'),
(3, 6, 'Event Propagation'),
(3, 6, 'Event Propagation'),
(3, 6, 'jQuery - Event Handling'),
(3, 6, 'Chrome DevTools (In-depth)'),
(4, 1, 'Getting Started'),
(4, 1, 'Flexbox'),
(4, 1, 'Flexbox Froggy'),
(4, 1, 'Flexbox Practice'),
(4, 1, 'External Font'),
(4, 1, 'Nav Layout'),
(4, 1, 'Adding the Header'),
(4, 1, 'Setup the main container'),
(4, 1, 'CSS Fundamentals'),
(4, 1, 'CSS'),
(4, 1, 'Crafting the Form'),
(4, 1, 'Web Forms'),
(4, 1, 'JavaScript in the Browser'),
(4, 2, 'DOM Events'),
(4, 2, 'DOM Events'),
(4, 2, 'Implement the character counter'),
(4, 2, 'Creating the tweets'),
(4, 2, 'Fixed Nav'),
(4, 2, 'What is Ajax?'),
(4, 2, 'Ajax with JQuery'),
(4, 2, 'Debugging with DevTools'),
(4, 3, 'Dynamic Tweets'),
(4, 3, 'Form Submission using JQuery'),
(4, 3, 'AJAX'),
(4, 3, 'Fetching tweets with Ajax'),
(4, 3, 'Form Validation'),
(4, 3, 'Refetch tweets on Submission'),
(4, 3, 'Cross-Site Scripting'),
(4, 3, 'Displaying Validation Errors With jQuery'),
(4, 3, 'jQuery'),
(4, 3, 'Form toggle'),
(4, 3, 'Add a Second Toggle Button'),
(4, 4, 'Responsive Design'),
(4, 4, 'Common Responsive Design Patterns'),
(4, 4, 'Responsive Design'),
(4, 4, 'Responsive Design'),
(4, 4, 'SASS'),
(4, 4, 'Submit Project for Evaluation'),
(4, 5, 'Programming Test 4'),
(4, 5, 'Introduction to Algorithms'),
(4, 5, 'Complexity: Elementary Operations and Running Time'),
(4, 5, 'Complexity'),
(4, 5, 'Linear vs Logarithmic Algorithms'),
(4, 5, 'Search Analysis'),
(4, 5, 'Quadratic'),
(4, 5, 'Quadratic'),
(4, 5, 'Complexity II'),
(4, 5, 'Big O Notation'),
(4, 5, 'Big O Notation'),
(4, 5, 'Google Interview'),
(4, 5, 'Hacker Rank Big O'),
(4, 5, 'Computational Complexity'),
(4, 5, 'Asymptotic Notation'),
(4, 6, 'What is a Database?'),
(4, 6, 'Intro to Relational Databases'),
(4, 6, 'Visualizing Databases'),
(4, 6, 'SQL Introduction'),
(4, 6, 'SQLZoo - Part I'),
(4, 6, 'SQL Fundamentals'),
(4, 6, 'More Advanced SQL Queries'),
(4, 6, 'SQLZoo - Part II - Joins'),
(4, 6, 'Relational queries in SQL'),
(4, 6, 'Modifying databases with SQL'),
(5, 1, 'Using PostgreSQL for M1'),
(5, 1, 'Using PostgreSQL'),
(5, 1, 'BootcampX'),
(5, 1, 'BootcampX Workflow'),
(5, 1, 'BootcampX Queries 1'),
(5, 1, 'BootcampX Assignments'),
(5, 1, 'JOINing Tables'),
(5, 1, 'A Visual Explanation of SQL Joins'),
(5, 1, 'BootcampX Queries II - JOIN'),
(5, 1, 'Group By and Having'),
(5, 1, 'BootcampX Queries 3 - Group By'),
(5, 1, 'Sub Queries'),
(5, 1, 'SELECT in SELECT'),
(5, 1, 'PGExercises'),
(5, 1, 'EXPLAIN! Query Plans'),
(5, 2, 'BootcampX Assistance Requests'),
(5, 2, 'BootcampX Queries 4'),
(5, 2, 'What is Database Design?'),
(5, 2, 'Database Normalization'),
(5, 2, 'Relationships Between Tables'),
(5, 2, 'Relational Databases'),
(5, 2, 'Creating ERDs'),
(5, 2, 'LighthouseBnB Intro'),
(5, 2, 'LighthouseBnB ERD'),
(5, 2, 'LighthouseBnB ERD Review'),
(5, 2, 'General Election Normalizing Data'),
(5, 2, 'Self JOIN'),
(5, 3, 'Data Definition Language'),
(5, 3, 'Data Manipulation Language'),
(5, 3, 'LighthouseBnB DDL'),
(5, 3, 'LighthouseBnB INSERT'),
(5, 3, 'LighthouseBnB More Data'),
(5, 3, 'LighthouseBnB SELECT'),
(5, 3, 'Node Postgres'),
(5, 3, 'SQL Injection'),
(5, 3, 'LighthBnB Web Boilerplate'),
(5, 3, 'Intro to Career Services Survey'),
(5, 3, 'LighthouseBnB More Tables'),
(5, 3, 'Using Null and Numerics'),
(5, 4, 'Programming Test #5 (SQL)'),
(5, 4, 'LighthouseBnB Users'),
(5, 4, 'LighthouseBnB Reservations'),
(5, 4, 'LighthouseBnB Properties'),
(5, 4, 'LighthouseBnB Add Property'),
(5, 4, 'Make a Reservation'),
(5, 4, 'Project Structure'),
(5, 4, 'You vs. Database'),
(5, 5, 'Collaboration with Git'),
(5, 5, 'Setup Local PG Database'),
(5, 5, 'Setup Git Repo'),
(6, 5, 'Midterm Project Evaluation'),
(6, 5, 'Installing Node'),
(6, 5, 'JSX In React'),
(6, 5, 'Building Our React App'),
(6, 5, 'Navigating React App Files'),
(6, 5, 'Quiz - Navigating React App Files'),
(6, 5, 'Tweeter in React'),
(6, 5, 'Cutting HTML Components'),
(6, 5, 'Creating React Components'),
(6, 5, 'Connecting Our Components'),
(6, 5, 'Importing HTML In Components'),
(6, 5, 'Differences Between HTML &amp; JSX'),
(6, 5, 'Converting Our HTML Content'),
(6, 5, 'Event Handling In React'),
(6, 5, 'Handling Events In React'),
(6, 5, 'JavaScript Patterns For React'),
(6, 6, 'Reading Data Structures'),
(6, 6, 'Creating Data Structures'),
(6, 6, 'React Props'),
(6, 6, 'Building Our React App'),
(6, 6, 'Meet Today''s Project: Tourney Matches'),
(6, 6, 'Creating Components'),
(6, 6, 'Building the Player and PlayerList Components'),
(6, 6, 'Building the Match and MatchList Components'),
(6, 6, 'Updating the App Component'),
(6, 6, 'Understanding The Data'),
(6, 6, 'Inserting The Data'),
(6, 6, 'Quiz - Understanding the Data'),
(6, 6, 'Passing Data Down with Props'),
(6, 6, 'Conditional Rendering'),
(6, 6, 'Refactoring Our App'),
(6, 6, 'Mapping Matches &amp; Players'),
(6, 6, 'Quiz - React Props'),
(7, 1, 'React State'),
(7, 1, 'Building Our React App'),
(7, 1, 'Today''s Project: Fancy Buttons!'),
(7, 1, 'Creating Components'),
(7, 1, 'Adding State To Our Components'),
(7, 1, 'Modifying The State'),
(7, 1, 'React State'),
(7, 1, 'Refactoring our State'),
(7, 1, 'Refactoring Our State'),
(7, 1, 'Better Parent State Modifications'),
(7, 1, 'Quiz: Refactoring Our State'),
(7, 1, 'Controlled Components'),
(7, 1, 'Fragments'),
(7, 1, 'Hello React'),
(7, 1, 'React'),
(7, 1, 'Styling Components'),
(7, 1, 'Interview Scheduler'),
(7, 1, 'Project Setup &amp; Familiarity'),
(7, 1, 'JavaScript Tooling'),
(7, 2, 'Why Storybook?'),
(7, 2, 'Building a Button'),
(7, 2, 'Testing our Button'),
(7, 2, 'Refactoring our Button'),
(7, 2, 'Listing Days'),
(7, 2, 'Building the DayListItem'),
(7, 2, 'Styling the DayListItem'),
(7, 2, 'Testing the DayListItem'),
(7, 2, 'Building the DayList'),
(7, 2, 'Updating our App'),
(7, 2, 'Adding State to our App'),
(7, 3, 'React Development Tools'),
(7, 3, 'Listing Interviewers'),
(7, 3, 'Building the Interviewer Item'),
(7, 3, 'Building the Interviewer List'),
(7, 3, 'Refactoring Interviewer Components'),
(7, 3, 'Controlled Lists'),
(7, 3, 'The Appointment Component'),
(7, 3, 'Our First Appointment Views'),
(7, 3, 'More Appointment Views'),
(7, 3, 'Appointment Form'),
(7, 3, 'Building the Appointment Form'),
(7, 3, 'Props and State in the Appointment Form'),
(7, 3, 'Displaying Appointments'),
(7, 3, 'The Schedule'),
(7, 4, 'The API Server'),
(7, 4, 'Client Requests and Handling Side Effects'),
(7, 4, 'Using Effects'),
(7, 4, 'Data Fetching with Axios'),
(7, 4, 'Axios and React'),
(7, 4, 'Requesting the Days'),
(7, 4, 'Transforming Data with Selectors'),
(7, 4, 'Managing State'),
(7, 4, 'Retrieving Appointments'),
(7, 5, 'Retrieving Interviewer Data'),
(7, 5, 'Custom Hooks'),
(7, 5, 'Building a Hook'),
(7, 5, 'Using our Custom Hook'),
(7, 5, 'Adding an Interviewers Selector'),
(7, 6, 'Automated Testing'),
(7, 6, 'Types of Tests'),
(7, 6, 'Test Driven Development'),
(7, 6, 'A Culture of Testing'),
(7, 6, 'React Deep Dive'),
(8, 1, 'Immutable Update Patterns'),
(8, 1, 'Creating Appointments'),
(8, 1, 'Deleting Appointments'),
(8, 1, 'Editing Appointments'),
(8, 1, 'Handling Errors'),
(8, 1, 'Separation of Concerns'),
(8, 1, 'Updating Spots Remaining'),
(8, 1, 'Reducers'),
(8, 1, 'The Case Against Switch'),
(8, 1, 'Using Reducers with React'),
(8, 1, 'Updating Spots Remaining with Reducers'),
(8, 1, 'Introducing WebSockets'),
(8, 1, 'Connecting to a WebSocket Server'),
(8, 2, 'Testing the Project'),
(8, 2, 'Type Checking with Prop Types'),
(8, 2, 'Testing React'),
(8, 2, 'Our First Test'),
(8, 2, 'Mocking'),
(8, 2, 'Our Test First'),
(8, 2, 'Test Coverage'),
(8, 2, 'Designing Integration Tests'),
(8, 2, 'Mocking Modules'),
(8, 2, 'Easier Async'),
(8, 2, 'Integration Testing'),
(8, 2, 'Debugging Tests'),
(8, 2, 'The Next Tests'),
(8, 2, 'Filling the Gaps'),
(8, 3, 'End to End Testing'),
(8, 3, 'Adding Cypress'),
(8, 3, 'Navigating Days'),
(8, 3, 'Designing E2E Tests'),
(8, 3, 'Writing Appointment Tests'),
(8, 3, 'Deploying the Server to Heroku'),
(8, 3, 'Continuous Pipeline'),
(8, 3, 'Connecting CircleCI to GitHub'),
(8, 3, 'Deploying the Client to Netlify'),
(8, 3, 'Submit Project for Evaluation'),
(8, 4, 'Class Components in the Wild'),
(8, 4, 'Scheduler Dashboard Setup'),
(8, 4, 'Loading Component'),
(8, 4, 'Panel Component'),
(8, 4, 'Handling State'),
(8, 4, 'Binding This'),
(8, 4, 'Adding Lifecycle to Classes'),
(8, 4, 'Everything Changes'),
(8, 4, 'Versions Managers'),
(8, 4, 'The Ruby Command Line'),
(8, 4, 'Learn X in Y Minutes'),
(8, 5, 'Learn Ruby The Hard Way'),
(8, 5, 'IRB Practice'),
(8, 5, 'Ruby Blocks'),
(8, 5, 'Benchmarking with Blocks'),
(8, 5, 'Enumeration with Candidates'),
(8, 5, 'Constants and Namespacing in Ruby'),
(8, 5, 'Closures in Ruby'),
(8, 6, 'Object-Oriented Programming in Ruby'),
(8, 6, 'Real World Learning'),
(8, 6, 'Ruby Style Guide'),
(9, 1, 'Submit Resume'),
(9, 1, 'Ruby &amp; Rails Installation'),
(9, 1, 'Instance Variables'),
(9, 1, 'Instance variables'),
(9, 1, 'TwO-O-Player Math Game - Planning'),
(9, 1, 'TwO-O-Player Math Game - Execution'),
(9, 1, 'Active Record'),
(9, 1, 'More AR - Stores and Employees'),
(9, 1, 'AR - Callbacks'),
(9, 1, 'AR - Callbacks Exercise'),
(9, 2, 'Older Versions'),
(9, 2, 'Tutorial: Getting Started with Rails'),
(9, 2, 'Data flow in MVC'),
(9, 2, 'Setup Jungle Project'),
(9, 2, 'Welcome to the Jungle'),
(9, 2, 'MVC Intro'),
(9, 3, 'ERB Introduction'),
(9, 3, 'Navigating Rails - Pro Tips'),
(9, 3, 'Bug: Money Formatting'),
(9, 3, 'UI Change: Empty Cart'),
(9, 3, 'UI Change: Sold Out Badge'),
(9, 3, 'UI Change: Order Details'),
(9, 3, 'Bug: Missing Admin Security'),
(9, 3, 'Feature: Admin Dashboard - Counts'),
(9, 3, 'Feature: About Page'),
(9, 4, 'Namespaces'),
(9, 4, 'Feature: Admin Categories'),
(9, 4, 'Database Migrations'),
(9, 4, 'Feature: User Authentication'),
(9, 4, 'EDD Rails Example - Part 1'),
(9, 4, 'EDD Rails Example - Part 2'),
(9, 4, 'EDD Rails Example - Part 3'),
(9, 5, 'Research and Reflect: An Introduction'),
(9, 5, 'RnR - An Example'),
(9, 5, 'RnR - Pick a Topic'),
(9, 5, 'RnR - Pick a Platform'),
(9, 5, 'RnR - Draft Writeup'),
(9, 6, 'RnR - Submit Draft This Week'),
(9, 6, 'RnR - Review Peer''s Draft'),
(9, 6, 'RnR - Finalize &amp; Submit'),
(9, 6, 'Intro to Rspec'),
(9, 6, 'Test Driven Development: A Love Story'),
(9, 6, 'Intro to Rspec and TDD'),
(10, 1, 'RSpec and BDD Tutorial'),
(10, 1, 'RSpec setup for Jungle'),
(10, 1, 'Model Spec: Product'),
(10, 1, 'Model Spec: User'),
(10, 2, 'How Companies Tests Rails Apps'),
(10, 2, 'Cypress Rails Setup'),
(10, 2, 'Feature Spec: Home Page'),
(10, 2, 'Feature Spec: Product Details'),
(10, 2, 'Feature Spec: Add to Cart'),
(10, 2, 'Feature Spec: User Login'),
(10, 3, 'Review and Submit Jungle'),
(10, 3, 'Ruby Programming Test'),
(10, 3, 'Feature: E-mail Receipt'),
(10, 3, 'Feature: Product Ratings'),
(10, 3, 'Feature: Inventory Adjustment'),
(10, 4, 'Final Project Planning');
