INSERT INTO workorders (user_student_id, user_mentor_id, status_id, category_id, module_id, environment, description, screenshot_url, link_to_module, escalate, mentor_notes, student_notes, mentor_rating, student_rating, date_created, date_pickup, date_closed)
VALUES
(1, 5, 2, 2, 6, 'M1',  'My final project team has been collaborating on changes, merges, pushes and pulls in GitHub, but I''d like to make use os the pull functionality. I don''t understand exactly how this works and would appreciate some assistance.', 'https://res.cloudinary.com/derw4ael5/image/upload/v1655675345/pfhnqwfcmem9nraeath5.png', 'https://web.compass.lighthouselabs.ca/days/w11d5', false, null, null, null, null, '2022-06-19T21:49:05.786Z', '2022-06-19T21:53:05.786Z', null),
(1, 5, 2, 1, 8, 'M1',  'I''ve completed the week 4 programming test, but I struggled with question #3. I got it to work, but would appreciate a code review.', 'https://res.cloudinary.com/derw4ael5/image/upload/v1655675455/ueaogfo1mjodo6hig0nq.png', 'https://web.compass.lighthouselabs.ca/days/w04d5/activities/976', false, null, null, null, null, '2022-06-19T21:50:55.826Z', '2022-06-19T21:56:05.786Z', null),
(1, null, 1, 6, 13, 'Vagrant',  'I installed some components through node for my current project and received a number of warnings and vulnerability messages. I''m not sure if I should be concerned about this and would like to discuss.', 'https://res.cloudinary.com/derw4ael5/image/upload/v1655675628/wcqtiqnevghg2myrjv87.png', 'https://web.compass.lighthouselabs.ca/days/w07d1/activities/1244', false, null, null, null, null, '2022-06-19T21:53:48.827Z', null, null),
(1, null, 1, 5, 16, 'Windows',  'I''m using a useEffect in my React application, but I''m getting errors when I try to compile. I can''t find the problem and would appreciate a second set of eyes.', 'https://res.cloudinary.com/derw4ael5/image/upload/v1655675744/win7imbmdgnfrpiqnmjo.png', 'https://web.compass.lighthouselabs.ca/days/w08d1/activities/1021', false, null, null, null, null, '2022-06-19T21:55:44.603Z', null, null),
(1, null, 1, 8, 6, 'Windows',  'Please help! I''ve been making changes to my application all day and just realized that I''ve been working in my main branch. My team is ready to merge and push all of our work and I don''t know what to do!', 'https://res.cloudinary.com/derw4ael5/image/upload/v1655675898/x0r9q1pgvtqsttonofbd.png', 'N/A', false, null, null, null, null, '2022-06-19T21:58:18.761Z', null, null),
(1, null, 1, 3, 5, 'Vagrant',  'I''m trying to run my application, but I''m receiving a proxy error when I try to launch it. I''m so confused, what''s a Proxy anyway? Do I even need it?', 'https://res.cloudinary.com/derw4ael5/image/upload/v1655676066/kx4j6hh3s7cpq7p2ifrn.png', 'https://web.compass.lighthouselabs.ca/days/w10d4/activities/546', false, null, null, null, null, '2022-06-19T22:01:06.707Z', null, null),
(1, null, 1, 3, 16, 'Vagrant',  'My React app is displaying a blank page in the browser and when I open the Inspect frame I can see that I''m receiving server errors. I don''t know where to even begin trying to debug this!', 'https://res.cloudinary.com/derw4ael5/image/upload/v1655676187/bep0nmfk9mppsdqsbk1h.png', 'https://web.compass.lighthouselabs.ca/days/w07d3/activities/1204', false, null, null, null, null, '2022-06-19T22:03:07.940Z', null, null),
(1, null, 1, 3, 13, 'M1',  'I''m receiving a bunch of warnings when I try to launch my app and I don''t understand the first thing about deciphering the messages form Node. Please, please help me...', 'https://res.cloudinary.com/derw4ael5/image/upload/v1655676297/vujkr19yqkro86sdw4y1.png', 'https://web.compass.lighthouselabs.ca/days/w03d3/activities/488', false, null, null, null, null, '2022-06-19T22:04:57.616Z', null, null),
(1, null, 1, 2, 1, 'M1',  'So I read the write up on Big O Notation and watched the videos, but I feel like I know less now than before. It seems like an important concept, but I just don''t understand. Could someone please explain?', 'https://res.cloudinary.com/derw4ael5/image/upload/v1655676472/ln3ugd8n1zdslicbsgjw.png', 'https://web.compass.lighthouselabs.ca/days/w04d5/activities/595', false, null, null, null, null, '2022-06-19T22:07:52.872Z', null, null);

